// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// file_type
Rcpp::CharacterVector file_type(Rcpp::CharacterVector files);
RcppExport SEXP _dqmagic_file_type(SEXP filesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type files(filesSEXP);
    rcpp_result_gen = Rcpp::wrap(file_type(files));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dqmagic_file_type", (DL_FUNC) &_dqmagic_file_type, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dqmagic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
