# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Get file types
#' @description Get file types based on the file's content.
#' @param files  Vector of file names including full or relative paths
#' @param mime_type  Logical indicating whether the MIME type should be returned
#' @param mime_encoding  Logical indicating whether the MIME encoding should be returned
#' @param magicfiles  Vector with file names to be used as magic file; the first
#'   usable file is selected
#' @return Vector of textual file type descriptions or MIME types/encodings
#' @export
file_type <- function(files, mime_type = FALSE, mime_encoding = FALSE, magicfiles = NULL) {
    .Call(`_dqmagic_file_type`, files, mime_type, mime_encoding, magicfiles)
}

#' @title Get libmagic version
#' @description Get version of the libmagic library as integer: MAJOR * 100 + MINOR.
#' @return Integer representing the version number
#' @export
magicVersion <- function() {
    .Call(`_dqmagic_magicVersion`)
}

#' @title Get default magic
#' @description Get paths for the default magic files and directories.
#' @return Paths of the default magic files and directories
#' @export
magicPathDefault <- function() {
    .Call(`_dqmagic_magicPathDefault`)
}

