# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Get file types
#' @description Get file types.
#' @param files  Vector of file names including full or relative paths
#' @return Vector of textual descriptions of file type
#' @export
file_type <- function(files) {
    .Call(`_dqmagic_file_type`, files)
}

