# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Get file types
#' @description Get file types.
#' @param files  Vector of file names including full or relative paths
#' @param mime_type  Logical
#' @param mime_encoding  Logical
#' @return Vector of textual descriptions or MIME types/encodings of file type
#' @export
file_type <- function(files, mime_type = FALSE, mime_encoding = FALSE) {
    .Call(`_dqmagic_file_type`, files, mime_type, mime_encoding)
}

